---
title: "CARMICHAEL_OregonBeesAndWildfires.rmd"
output: pdf_document
date: "2024-10-26"
---

# General topic of interest in relation to the Oregon Bee Atlas data 
We want to focus our project on the impact of wildfires and how their devastation of ecosystems influences bee populations.

# Potential questions within that topic area
How does species richness in bee populations differ in areas affected by recent wildfires? We can compare this to areas that are left unaffected.
How fast do bee populations recover in areas affected by wildfires? How do these timelines differ between habitats?
Does wildfire severity play a role in bee abundance and richness?
What traits make bees more resilient to wildfires/ ecological disturbances?
How do bee and Native plant species differ in areas before and after wildfires?
How does the availability of Native floral resources post-wildfire ecosystems influence bee populations?
Does wildfire affect the patterns of seasonal bee behaviors? 

# Potential additional datasets within that topic area (e.g., specify relevant government databases, academic data repositories, etc)

iNaturalist
Oregon Bee Atlas
Oregon Department of Forestry Fire History
Oregon Department of Forestry Data Hub
Bee Trait Data
Oregon Flora
East Multnomah Soil and Water Conservation District
NOAA
PRISM Climate Group
USGS Earth Explorer
Monitoring Trends In Burn Severity (MTBS)
Oregon Spatial Data Library

# The name of your partner 
Ali Carmichael
Vincent Cortes

# The name of your partner, and what parts of this assignment they contributed to, and what parts they wrote. 

Ali Carmichael - Contributed to potential questions within the topic area and also potential additional data sets.

Vincent Cortes - Contributed to potential questions within the topic area and also potential additional data sets. 

# workflow plan
I. Literature review
In Oregon, recent data shows a clear increase in wildfire frequency and intensity, largely due to extreme heat, drought frequency, and less cold weather caused by climate change. Increased temperature and lack of moisture in fire fuel like trees, shrubs, grasses, and forest debris can create several factors required to fuel large-scale fires. According to Oregon Climate Assessments, Oregon saw more days per year near 90 degrees between 2011 and 2020 than between 1951 and 2010 (Rojas). Since 2015, Oregon has experienced significant, record-breaking wildfire seasons that have led to massive destruction and ecosystem disruptions. A study cited by the National Oceanic and Atmospheric Administration (NOAA) found that climate change has doubled the area burned in western U.S. forests between 1984 and 2015. Furthermore, research shows that an average annual increase in temperature of 1 degree Celsius could increase the median burned area per year by as much as 600% in some forests (NOAA). Ongoing warming could continue amplifying fire seasons, posing long-term threats to Oregon’s forest and wildlife. 
According to the USDA, pollinators such as bees, butterflies, and birds pollinate around three-fourths of the world’s flowering plants, making pollinators essential for biodiversity (USDA Pollinators). The increase in wildfires, especially in regions like Oregon, poses a significant threat to pollinators. Wildfires are responsible for habit loss that has contributed to the decline of many pollinator species (USDA Pollinators). Fire can disrupt the balance of ecosystems and reduce plant diversity that pollinator species, especially bees, rely on to survive. In some cases, natural wildfires can benefit pollinators by promoting the growth of smaller, low-growing, flowering plants that support diverse bee populations. However, with the increase of recent wildfire activity, any potential benefit from these fires may be outweighed by the harm they cause to pollinator species, especially bees. 

https://www.pdx.edu/news/latest-climate-assessment-says-oregon-getting-warmer-whats-mean-state
https://www.noaa.gov/noaa-wildfire/wildfire-climate-connection

https://www.usda.gov/peoples-garden/pollinators#:~:text=Three%2Dfourths%20of%20the%20world's,bites%20of%20food%20you%20eat.

Past work and data available

Wilkin et al. (2021) in Biological Conservation explore how wildfires affect declining pollinator communities. This research is useful to our study, as it explores changes in pollinator species richness and diversity after wildfires in various forest ecosystems. For example, the paper illustrates that intense, frequent fires can significantly reduce floral resources pollinators need to survive, affecting populations long-term. Using this study, we can consider how similar effects might impact Oregon pollinators with the surge of wildfire activity in various regions of Oregon.

Ponisio et al. (2016) discuss the effects of ecosystem disturbances, including wildfire, on bee biodiversity. This paper explores the concept that while some disturbance may potentially benefit pollinator populations by promoting the growth of specific plant species that thrive post-fire, excessive, intense, and poorly managed fires can lead to habitat destruction. The study illustrates the complexity of fires and their disturbances. This is shown by the ability of certain bee species to thrive in post-fire environments, while other species’ populations may decline. Using this approach, we can understand and highlight the importance of balancing the management of fire-prone regions in Oregon.

https://www.ponisiolab.com/uploads/9/4/6/4/94640692/wilkin-317.pdf
https://www.sciencedirect.com/science/article/pii/S0006320721003177?via%3Dihub

iNaturalist: Provides observations of native species in different regions of the Western U.S. that provide insight into what native plant species thrived in pre and post-fire environments in areas with known fires. 

Oregon Department of Forestry Fire History: Offers detailed records of past fires in Oregon that can be used when correlating fire events with changes in pollinator populations. 

Oregon Flora: Provides information on native flora in different regions of Oregon. This could be useful in identifying what species of native plants thrive in post-fire environments.

Oregon Spatial Data Library: Include geographical and satellite imagery which can help visualize fire-affected areas and understand the landscape changes before and after fires that may influence pollinator habitats.

Purpose of the study
Further refine your approach (e.g., what data will you combine, how will you address the question)


Justify why this is needed now (e.g., visualization to test a new dimension of the question or better convey an old one)

Hypotheses/questions
List these clearly and in a logical order


Make hypotheses directionally using predictions (e.g. “I predict urbanization will reduce plant diversity” rather than “I predict urbanization will change plant diversity”)

II. Dataset identification
Please identify the additional datasets you will be using to address your question. * Provide the data source (including web url) * Describe sufficient metadata to convey who collected the data, how it was collected, and what each column contains.
III. Workflow plan
In pros, please describe the workflow you will use tidy your raw data, manipulate and summarize it in relevant ways, test you hypothesis, and visualize it.The goal here is to develop a logic to your workflow before you code. * Include any needed cleaning steps (e.g., “remove non-species such as ‘fly’ from the species column”) * Include any aggregation steps (e.g., “count the number of entries by region and year to calculate species richness”). * Include descriptions of any functions/for loops you will write.
* Include a description the the statistical test you will use, and how you will apply it programatically (i.e., I will simulate the null hypothesis by shuffling the labels…“)
 
IV. Partner contributions
Each person will turn in a separate document, though the above content will be the same. Here, summarize how each partner contributed. Ex: "We met and discussed the workflow plan together and wrote it together. We both made an annotated bibliography of the available studies, and then I summarized them. My partner reviewed what I wrote and edited it. My partner drafted the purpose of the study, and I gave edits."
