---
title: "Proposed workflow"
author: "Vincent Cortes and Ali Carmichael"
date: "2024-11-13"
output: pdf_document
---
**I. Literature review**\
**Introduction**\

In Oregon, recent data shows a clear increase in wildfire frequency and intensity, largely due to extreme heat, drought frequency, and less cold weather caused by climate change. Increased temperature and lack of moisture in fire fuel like trees, shrubs, grasses, and forest debris can create several factors required to fuel large-scale fires. According to Oregon Climate Assessments, Oregon saw more days per year near 90 degrees between 2011 and 2020 than between 1951 and 2010 (Rojas). Since 2015, Oregon has experienced significant, record-breaking wildfire seasons that have led to massive destruction and ecosystem disruptions. A study cited by the National Oceanic and Atmospheric Administration (NOAA) found that climate change has doubled the area burned in western U.S. forests between 1984 and 2015. Furthermore, research shows that an average annual increase in temperature of 1 degree Celsius could increase the median burned area per year by as much as 600% in some forests (NOAA). Ongoing warming could continue amplifying fire seasons, posing long-term threats to Oregon’s forest and wildlife. 
According to the USDA, pollinators such as bees, butterflies, and birds pollinate around three-fourths of the world’s flowering plants, making pollinators essential for biodiversity (USDA Pollinators). The increase in wildfires, especially in regions like Oregon, poses a significant threat to pollinators. Wildfires are responsible for habit loss that has contributed to the decline of many pollinator species (USDA Pollinators). Fire can disrupt the balance of ecosystems and reduce plant diversity that pollinator species, especially bees, rely on to survive. In some cases, natural wildfires can benefit pollinators by promoting the growth of smaller, low-growing, flowering plants that support diverse bee populations. However, with the increase of recent wildfire activity, any potential benefit from these fires may be outweighed by the harm they cause to pollinator species, especially bees. 

**Past work**\

**Wilkin et al. (2021)** in Biological Conservation explore how wildfires affect declining pollinator communities. This research is useful to our study, as it explores changes in pollinator species richness and diversity after wildfires in various forest ecosystems. For example, the paper illustrates that intense, frequent fires can significantly reduce floral resources pollinators need to survive, affecting populations long-term. Using this study, we can consider how similar effects might impact Oregon pollinators with the surge of wildfire activity in various regions of Oregon.

**Stephen et al. (2016)** discuss the effects of ecosystem disturbances, including wildfire, on bee biodiversity. This paper explores the concept that while some disturbance may benefit pollinator populations by promoting the growth of specific plant species that thrive post-fire, excessive, intense, and poorly managed fires can lead to habitat destruction. The study illustrates the complexity of fires and their disturbances. This is shown by the ability of certain bee species to thrive in post-fire environments, while other species’ populations may decline. Using this approach, we can understand and highlight the importance of balancing the management of fire-prone regions in Oregon.

**Other data available**\

**iNaturalist:** Provides observations of native species in different regions of the Western U.S. that provide insight into what native plant species thrived in pre and post-fire environments in areas with known fires. \

**Oregon Department of Forestry Fire History:** Offers detailed records of past fires in Oregon that can be used when correlating fire events with changes in pollinator populations. \

**Oregon Flora:** Provides information on native flora in different regions of Oregon. This could be useful in identifying what species of native plants thrive in post-fire environments.\

**Oregon Spatial Data Library:** Include geographical and satellite imagery which can help visualize fire-affected areas and understand the landscape changes before and after fires that may influence pollinator habitats.\

**Purpose of the study**\

Our study looks at the recovery of bee populations in areas affected by wildfires, focusing specifically on the 2020 wildfire season. We selected 2020 because it provides the most recent data while allowing enough time for bee and plant communities to reestablish in affected areas. To investigate recovery patterns, we will analyze data from the Oregon Bee Atlas, which includes details on bee species, their locations, and the plants they associate with (Oregon Bee Project, 2023). This information is essential for identifying which bee species recover first and the specific plants they are associated with in post-fire zones. Fire zone data from the Oregon Department of Forestry will be used to identify burned areas and classify habitat types impacted by wildfires (Oregon Department of Forestry, 2023). By combining these datasets, we want to compare recovery timelines across different habitats and assess changes in bee and native plant species diversity before and after wildfires. This study will help bring attention to the ecological endangerment of bee populations and provide bee conservationists with insights to better assist our pollinating friends in becoming more resilient to wildfires.


Pollinators, especially bees, are vital to ecosystem health and especially agricultural productivity. Bees play an essential role in the pollination of many plants, including crops. As discussed earlier, bees are in charge of pollinating a little over a third of US crops. The heavy reliance on pollinators means we are obligated to protect them. According to the Environmental Defense, As climate change intensifies, extreme heat and drought conditions are leading to more frequent and severe wildfires (EDF). These fires cause widespread destruction to habitats, affecting both flora and fauna and threatening the survival of pollinator populations. Given the growing ecological threats caused by climate change, there is an urgent need to understand how bee populations recover in post-fire environments and identify factors that support resilience. Visualizing recovery patterns across different habitats using spatial data can provide helpful insights into which ecosystems and native plants foster quicker bee recovery. 


**Hypotheses/questions**\


The goal of this project is to answer the following questions about how wildfires affect bee populations and the flora they interact with.\


**Question1:**\
How fast do bee populations recover in areas affected by wildfires? How do these timelines differ between habitats?\
**Hypotheses**\
We anticipate that the bee populations will recover faster in grasslands compared to forested habitats.\
We predict that habitats with greater plant diversity will support a faster rate of recovery of bee populations after wildfires than those that have a lower plant diversity.\

**Question2:**\
How do bee and Native plant species differ in areas before and after wildfires?\
**Hypotheses**\
We expect the composition of bee and native plant species in a post-fire setting to differ significantly from that of a pre-fire setting.\
We also predict that the bee species in post-fire areas will associate with early-successional plant species that can colonies and then transmit to more diverse flora as recovery accelerates.\

**II. Dataset identification**\
We will use data sets from the Oregon Bee Atlas naturalist observations like OBA List of iNaturalist bee species observations and OBA List of iNaturalist plant species observations. These two data objectives were to identify and catalog native bee species throughout Oregon. The data was collected by trained volunteers. They uploaded observations to iNaturalist OBA project. The data sets contain information on its taxonomy, species name, location, time, and much more information we probably won't need. We will also use ODF List of all fires in Oregon dataset to determine what fires we would like to focus on. This dataset has all fires reported in Oregon in 2020. This dataset includes fields like forename, location, size of fire, fire type, land ownership, and so much more information that will not be needed. When downloading these datasets, we could filter out all non-relevant information to reduce file size.

**III. Workflow plan**\
**Data Cleaning**\
First, we will clean the datasets we will be using by filtering for only relevant data. From the iNaturalist dataset, we will keep only the bee and native plant species observations in Oregon, specifically areas affected by wildfires between 2016 and 2020. Additionally, we will remove entries with missing or incomplete data for the important fields we will be looking at like species ID, location, and observation date. From the Oregon fire dataset, we will extract data on wildfire locations and dates, focusing on years relevant to our iNaturalist observations. 

**Data Manipulation and Summarization**\
To explore trends in bee diversity over time and across different regions, we will aggregate the data by year and region. We will determine the species richness in different regions affected by fires. We will also summarize the data by averaging the number of observations per species per year to assess changes in populations following wildfire events. 

**Hypothesis Testing**\
To evaluate if there are statistically significant differences in bee populations and species diversity pre and post-wildfire across different habitats we will follow this form of hypothesis testing: \
Create comparison groups\
Question 1: Separate data into different habitats and then create a new column, pre- and post-wildfire for each habitat.\
Question 2: Create a new column for our species data, pre- and post-wildfire to compare the species diversity and recovery over time.\
We will use an A/B approach to simulate the null hypothesis; the observed differences in bee population density and species diversity are not due to the effect of wildfire on habitat diversity. We will do this by shuffling the labels for pre- and post-wildfire observations to create randomized datasets for each hypothesis.
**A/B Testing**\
Hypothesis 1: Shuffle pre/post labels within each habitat to assess bee population density changes
Hypothesis 2: Shuffle pre/post labels across different species to observe species diversity and richness changes.
For each test, we will then calculate the test statistic. For question one we will calculate the mean difference in populations for different habitats, and for question two we will calculate the mean difference in species diversity and richness. We will repeat the simulation process for a large number of samples to generate our distribution of test statistics under the null. We can then calculate the p-value by comparing the observed statistic to our simulated data and finding the proportion of test statistics that are as extreme or more extreme than the observed value. To do this, we will use a p-value at a significance level of 0.05. 

**Data Visualization**\
To communicate our results, we will create several visualizations. First, we will create line plots to show changes in species richness over time. These line plots will have separate lines for regions before and after the effects of a fire. Then, we will use bar plots to compare the average species richness between fire-impacted and control regions for each year post-fire. We will use different colors to distinguish between regions and illustrate the extent of fire impact. 

**Code Descriptions**\
For our project, we will write several functions to help our code function efficiently. We will write a function that will calculate the species richness for different regions of our iNaturalist dataset called species_richness. Another function named pre_and_post_fire will help us categorize our datasets based on the wildfire dates and locations and assign the given labels. For our A/B testing, we will create a shuffle_labels function to perform our simulation making it easier to do a large simulation. Finally, we will structure these functions in a way that they can be applied across all of the datasets we will be using to improve functionality and make it easier to replicate.  



**IV. Partner contributions**\
**Ali Carmichael** - Wrote the introduction paragraphs as well as the annotated bibliography for the past works. Found other data to use and wrote a brief description of each dataset. Brainstormed ideas for the workflow plan and then wrote out the proposed workflow. \

**Vincent Cortes**- Worked on the purpose of the study and hypotheses paragraphs. Also found datasets for the dataset identification along with writing it.\



**Works Cited**\
“The Importance of Pollinators.” USDA, https://www.usda.gov/peoples-garden/pollinators. Accessed 12 November 2024.\

Rojas, Cristina. “LATEST CLIMATE ASSESSMENT SAYS OREGON IS GETTING WARMER — WHAT'S THAT MEAN FOR THE STATE?” Portland State University, 21 January 2023, https://www.pdx.edu/news/latest-climate-assessment-says-oregon-getting-warmer-whats-mean-state.\

Stephen, Mason C., et al. “Responses from bees, butterflies, and ground beetles to different fire and site characteristics: A global meta-analysis.” Biological Conservation, vol. 261, 2021, https://www.sciencedirect.com/science/article/pii/S0006320721003177?via%3Dihub.\

“Wildfire climate connection.” National Oceanic and Atmospheric Administration, https://www.noaa.gov/noaa-wildfire/wildfire-climate-connection. Accessed 12 November 2024.\

“Wildfires.” Environmental Defense Fund, https://www.edf.org/climate/heres-how-climate-change-affects-wildfires. Accessed 12 November 2024.\

Wilkin, Katherine M., et al. “DECADE-LONG PLANT COMMUNITY RESPONSES TO SHRUBLAND FUEL HAZARD REDUCTION.” Fire Ecology, vol. 13, no. 2, 2017, pp. 105-136, https://www.ponisiolab.com/uploads/9/4/6/4/94640692/wilkin-317.pdf.\
